### ISSUE TITLE
Define a flow starting from a textual representation

### ISSUE THREAD

**Issue by latitude-oss** [pipelite-projects/pipelite-framework#1]
**Current behavior**

There is no way to define a Flow from a textual representation.

**Expected behavior**

As a developer, I expect to get a serialized form of a Flow and to reconstruct a Flow from its serialized form.

**Describe the solution you'd like**

This could be an ipothesis to describe the flow in a textual manner

```
apiVersion: flow/v1
kind: Flow
metadata:
  name: "TestFlow"
specs:
  source: "http://ingress"
  nodes:
  	- type: "process"
  	  name: "step-1"
  	  impl: >
  	    function process(ioContext, processContribution){\n
  	    	/* processor logic here */
  	    }\n
  sink: "slf4j://main-logger"
```

More details on API definition to discuss.

**Additional context**

* Project Version: 0.1.0
* Java Version: 17
